modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerUrl = ""
[[mods]]
modId = "colorchat"
version = "1.0.0"
displayName = "ColorChat"
logoFile = ""
credits = ""
authors = "j3ly"
description = "Color chat mod with ranks and per-player colors"
